language: node_js

node_js:
  - 'node'

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - "npm install"

# Init GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - "npm run lint:lib"
  - "npm run test:lib"
  - "npm run build:lib"

cache:
  directories:
     - "./node_modules"

before_deploy:
  - "npm run build:example"
  - "cd ./dist/ng-drag-drop-list/"

deploy:
  - provider: script
    script:
      - "cd../../ &&  npm run deploy:gh-pages"
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: $EMAIL_ADDRESS
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
